services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cherry-app
    restart: unless-stopped
    tty: true
    command: ["python3 app.py"]
    volumes:
      - .:/home/cherrymusic
    networks:
      - cherrymusic

  redis:
    image: redis:latest
    container_name: cherry-redis
    restart: unless-stopped
    networks:
      - cherrymusic

networks:
  cherrymusic:
